/*
 * Creation : 2 mars 2018
 */
package constante;

public enum SecondaryKeywords {
    ANNOTATION, ANNOTATION_LABEL, ANNOTATION_ORIGIN, ANNOTATION_TEXT, AXIS_DESCR, AXIS_PTS_REF, BIT_MASK, BYTE_ORDER, CALIBRATION_ACCESS, COEFFS, COEFFS_LINEAR, COMPARISON_QUANTITY, COMPU_TAB_REF, CURVE_AXIS_REF, DEFAULT_VALUE, DEFAULT_VALUE_NUMERIC, DEPENDENT_CHARACTERISTIC, DEPOSIT, DISCRETE, DISPLAY_IDENTIFIER, ECU_ADDRESS_EXTENSION, EXTENDED_LIMITS, FIX_AXIS_PAR, FIX_AXIS_PAR_DIST, FIX_AXIS_PAR_LIST, FORMAT, FORMULA, FORMULA_INV, MATRIX_DIM, MAX_GRAD, MAX_REFRESH, NUMBER, PHYS_UNIT, PROJECT_NO, READ_ONLY, REF_UNIT, VERSION;
}
